[versions]
kotlin = "2.0.20"

jvm = "17"
agp = "8.6.0"

[plugins]
android_application = { id = "com.android.application", version.ref = "agp" }
kotlin_android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin_compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

[libraries]
activity = { module = "androidx.activity:activity-ktx", version = "1.9.2" }
core_ktx = { module = "androidx.core:core-ktx", version = "1.13.1" }

immutable = { group = "org.jetbrains.kotlinx", name = "kotlinx-collections-immutable", version = "0.3.7" }

compose_bom = { module = "androidx.compose:compose-bom", version = "2024.09.00" }
compose_foundation = { module = "androidx.compose.foundation:foundation", version = "1.7.0" }
compose_ui = { module = "androidx.compose.ui:ui" }

compose_activity = { module = "androidx.activity:activity-compose", version = "1.9.2" }
compose_material3 = { module = "androidx.compose.material3:material3", version = "1.3.0" }

desugaring = { module = "com.android.tools:desugar_jdk_libs", version = "2.1.2" }